services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:3000"
    volumes:
      - .:/app
      # Persist node_modules to avoid unnecessary npm installs
      - node_modules:/app/node_modules
      # Persist Next.js build cache
      - .next:/app/.next
    environment:
      - NODE_ENV=development
    command: bun run dev
    networks:
      - omnidine

networks:
  omnidine:
    name: omnidine-backend_sail
    external: true

volumes:
  # Named volume for node_modules to persist between restarts
  node_modules: